from flask import Flask, render_template, request, Response, jsonify
from flask_cors import CORS
from typing import Generator
from langchain_core.prompts import ChatPromptTemplate
from langchain_ollama import ChatOllama
from langchain_core.output_parsers import StrOutputParser

app = Flask(__name__)
CORS(app)

# Initialize local model
llm = ChatOllama(model="qwen3:1.7b", temperature=0.7)

# Standard conversational template
prompt = ChatPromptTemplate.from_template("You are a helpful AI assistant. Answer the user: {user_input}")

from memory import get_history_context, add_message

# Build the chain
chain = prompt | llm | StrOutputParser()

def stream_response(user_input: str, session_id: str = "default") -> Generator[str, None, None]:
    """Generator function that yields tokens as they are generated by Ollama."""
    try:
        # Try to get memory context
        context = get_history_context(session_id)
        
        # Seamlessly integrate history if it exists
        if context:
            augmented_input = f"{context}\nCurrent User Message: {user_input}"
        else:
            augmented_input = user_input
            
        # Add user message to history
        add_message("user", user_input, session_id)
        
        # Capture the full AI response to add to memory later
        ai_response = ""
        for chunk in chain.stream({"user_input": augmented_input}):
            ai_response += chunk
            yield chunk
            
        # Add assistant response to history
        add_message("assistant", ai_response, session_id)
        
    except Exception as e:
        # Fallback: Gracefully process as single-turn message if anything fails
        print(f"Memory integration failed, falling back to single-turn: {e}")
        for chunk in chain.stream({"user_input": user_input}):
            yield chunk

@app.route("/")
def index():
    """Render the main chat interface."""
    return render_template("index.html")

@app.route("/chat", methods=["POST"])
def chat():
    """Handle incoming chat messages from the frontend."""
    data = request.get_json()
    user_message = data.get("message")
    session_id = data.get("session_id", "default")
    
    if not user_message:
        return jsonify({"error": "No message provided"}), 400
    
    # Return a streaming response using the generator
    return Response(stream_response(user_message, session_id), mimetype='text/plain')

if __name__ == "__main__":
    # Run the Flask development server
    app.run(debug=True, port=5000)
