from typing import Generator
from langchain_core.prompts import ChatPromptTemplate
from langchain_ollama import ChatOllama
from langchain_core.output_parsers import StrOutputParser

llm = ChatOllama(model="qwen3:1.7b")
prompt = ChatPromptTemplate.from_template("Write a short story about {topic}.")

# Build the chain
chain = prompt | llm | StrOutputParser()

def stream_response(topic: str) -> Generator[str, None, None]:
    """Generator function that yields tokens as they are generated by Ollama."""
    for chunk in chain.stream({"topic": topic}):
        yield chunk

if __name__ == "__main__":
    # Consuming the generator:
    for token in stream_response("a lost astronaut"):
        print(token, end="", flush=True)
    print()